-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM AUTHOR A, BOOK B, BOOK_SALES S
WHERE A.AUTHOR_ID = B.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID 
    AND S.SALES_DATE LIKE '2022-01-%'
GROUP BY A.AUTHOR_ID, B.CATEGORY 
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC