-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R1
WHERE FAVORITES = (SELECT MAX(R2.FAVORITES) FROM REST_INFO R2 WHERE R2.FOOD_TYPE = R1.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;