-- 코드를 입력하세요
WITH HEAVY AS(
    SELECT HOST_ID AS HEAVY_HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
)

SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (SELECT * FROM HEAVY)
ORDER BY ID