-- 코드를 입력하세요
WITH JULY_ORDER AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FH.FLAVOR
FROM FIRST_HALF FH JOIN JULY_ORDER JO ON FH.FLAVOR = JO.FLAVOR
ORDER BY FH.TOTAL_ORDER + JO.TOTAL_ORDER DESC
LIMIT 3
