-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOATAL_SALES
FROM 
    USED_GOODS_USER UGU
    JOIN USED_GOODS_BOARD UGB ON UGU.USER_ID = UGB.WRITER_ID
WHERE 
    STATUS = 'DONE'
GROUP BY 
    USER_ID
HAVING 
    SUM(PRICE) >= 700000
ORDER BY
    SUM(PRICE) ASC;