-- 코드를 작성해주세요
WITH MAX_TABLE AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS MAX_YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        MAX_YEAR
)

    
SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA E JOIN MAX_TABLE M ON YEAR(E.DIFFERENTIATION_DATE) = M.MAX_YEAR
ORDER BY
    YEAR, YEAR_DEV