-- 코드를 작성해주세요

SELECT 
    SUM(SCORE) AS SCORE, 
    HG.EMP_NO, 
    HE.EMP_NAME, 
    HE.POSITION, 
    HE.EMAIL
FROM 
    HR_GRADE HG JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO
GROUP BY 
    HG.EMP_NO
ORDER BY 
    SUM(SCORE) DESC
LIMIT 1;