-- 코드를 입력하세요
SELECT F1.CATEGORY, F1.PRICE AS MAX_PRICE, F1.PRODUCT_NAME
FROM FOOD_PRODUCT F1
WHERE F1.CATEGORY IN ('과자', '국', '김치', '식용유')
      AND F1.PRICE = (
          SELECT MAX(F2.PRICE) 
          FROM FOOD_PRODUCT F2 
          WHERE F1.CATEGORY = F2.CATEGORY
      )
ORDER BY F1.PRICE DESC;