-- 코드를 작성해주세요
# SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# WHERE LENGTH >= AVG(LENGTH)


SELECT 
    COUNT(*) AS FISH_COUNT, 
    MAX(F1.LENGTH) AS MAX_LENGTH, 
    F1.FISH_TYPE
FROM FISH_INFO F1 
        JOIN (
            SELECT FISH_TYPE, AVG(LENGTH) AS AVG_LENGTH
            FROM FISH_INFO 
            GROUP BY FISH_TYPE
        ) F2 ON F1.FISH_TYPE = F2.FISH_TYPE
WHERE 
    F2.AVG_LENGTH >= 33
GROUP BY 
    F1.FISH_TYPE
ORDER BY 
    F1.FISH_TYPE;
